### ISSUE TITLE
Svelte somehow renders a margin in all components.

### ISSUE THREAD

**Issue by VentGrey** [UpVent/upventrs#2]
When rendering the Svelte components, a small margin (around 5px) is rendered in compnents that need the entire screen. This might be due to viewport issues or an issue with Sveltestrap.

## How to reproduce

Add the `shadow` class to the `Navbar.svelte` component. 

## Screenshot
![Error](https://user-images.githubusercontent.com/24773698/146667539-51158f92-fa87-401e-bbba-27711360c5b9.png)
![Error2](https://user-images.githubusercontent.com/24773698/146667540-7b1ed314-9f5e-4323-a655-8aa5132e875a.png)

**Comment by oliverloops** [comment]
Check out your global stylesheet or modify your main/global component styles adding:

`*, body {
     box-sizing: border-box;
}`

When we refer to viewport, we have 2 important attributes around box-sizing. these ones are content-box and border-box, the first one is the default one and adds an extra margin to every parent element, the second one keep the original element size and reduces to 0 any margin around it.

**Comment by VentGrey** [comment]
Tried this solution but it didn't 
work properly. I thought this was sveltestrap's fault but even tailwind presents this issue. 

![cosa](https://user-images.githubusercontent.com/24773698/146866835-2b0c9eeb-484a-4eab-9529-ceb41343d441.png)
